# Generated by Django 3.1.5 on 2021-01-08 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_tweet_id', models.IntegerField(default=None, null=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('text', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='img')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
