# Generated by Django 3.1.5 on 2021-01-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0008_auto_20210112_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='parent_tweet_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
